### ISSUE TITLE
Pip wheels for python 3.11

### ISSUE THREAD

**Issue by KhDenys** [reinterpretcat/vrp#142]
Hi @reinterpretcat, could you build pip wheels for the latest vrp version? Looks like 1.23 has build for python 3.10 only.
Thanks

**Comment by uptickmetachu** [comment]
Is it possible to drop support for python 3.6?

**Comment by uptickmetachu** [comment]
```
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./vrp-cli
          target: ${{ matrix.target }}
          sccache: 'true'
          args: --release --out dist -m Cargo.toml -i 3.7 3.8 3.9 3.10 3.11 3.12
```
Something like this will work (it will ignore python 3.6)
@reinterpretcat
